### ISSUE TITLE
Proposal  Peer Review - ViZiT

### ISSUE THREAD

**Issue by junaidhussain22** [INFO-526-FA24/project-2-dream-jobs#1]
1.Full names and githubnames of reviewing team-
- Sree Krishnaprasad : @SreeKrishna17
- Syed Junaid Hussain: @junaidhussain22
- Anushree Biswas: @anu3biswas
- Sumel Rattan: @SumelRattan

2. Describe the goal of the project
The project aims to analyze the U.S. job market to identify trends, skills, and career pathways, providing actionable insights to guide students in making informed career decisions post-graduation

3. Describe the data used or collected.
The dataset comprises of various attributes related to job postings, including job details such as titles, required experience, qualifications, salary ranges, locations, employment types, posting dates, company information, skills, and specific preferences, aiming to capture comprehensive information about the U.S. job market.

4. Describe how the research question will be answered, e.g. what approaches / methods will be used.-
They plan to collect real time data from various job- sites using web scraping techniques and use Machine learning and natural language processing techniques to extract insights, such as in-demand skills, emerging job roles, and location-based salary expectations.

5. Is there anything that is unclear from the proposal?
The team has indicated plans to scrape job market data; however, the specific domain or job roles targeted for data collection remain unclear. Given the vast number of professions in the job market, it would be beneficial to focus on a specific domain or set of job types. Narrowing down the scope will lead to a more targeted and insightful dataset, rather than a broad, generalized representation of the job market. The methodology mentions using machine learning and NLP techniques, but it's unclear how these will be applied.

6. Provide constructive feedback on how the team might be able to improve their project.
Overall, the proposal effectively captures the essence of comprehensive data analysis, including the integration of machine learning. However, as previously noted, narrowing down the scope to focus on specific job roles or domains will enhance the quality and relevance of the dataset. Additionally, it would be beneficial to outline the techniques you plan to use for data cleaning after web scraping to make the proposal more thorough and cohesive.
One intriguing direction to explore could be analyzing which job portals lead to the highest conversion rates, as well as identifying the types of roles that are most frequently filled through specific hiring platforms. This would add valuable insights into the effectiveness of different job portals and the popularity of various job roles.

7. What aspect of this project are you most interested in and would like to see highlighted in the presentation.- 
The most interesting part of this project is the focus on comparing what students want in their careers with actual job market trends. We would love to see the presentation highlight how analyzing job postings and student surveys can reveal which skills, salaries, and job locations are most in demand. This will help students better understand what the job market expects and how they can prepare for it.

8. Provide constructive feedback on any issues with file and/or
code organization.-
Structure looks okay but a section on EDA (different plots to showcase the analysis)  could have been included.

**Comment by Lucifer970901** [comment]
We appreciate the suggestion to narrow our scope. To better align with this feedback, we plan to conduct a student survey to understand which specific industries or job roles are of most interest. This will help us focus our analysis on areas that are directly relevant to students career aspirations, making the insights more targeted and actionable.

We plan to implement data cleaning techniques as outlined previously to ensure high-quality data. The analysis will be performed using EDA techniques in R, allowing us to create comprehensive visualizations that highlight trends, such as:
Skill demands in various industries.
Salary expectations across locations.
Popular job roles in relation to student interests.
We appreciate your feedback, which has been invaluable in refining our approach. By incorporating a student survey and focusing on EDA techniques in R, we aim to deliver targeted and actionable insights that align with students’ career interests. Thank you for helping us enhance the scope and clarity of our project!
