### ISSUE TITLE
4x4 Review

### ISSUE THREAD

**Issue by tanmaynaik11** [INFO-526-FA24/project-2-dream-jobs#10]
Feedback:
Background image is making the text readability difficult.
Good interpretation and storytelling.

**Comment by SohanicX** [comment]
Thank you for your feedback! We're pleased to hear that the interpretation and storytelling aspects were well-received.

We’ve noted your concern about the background image affecting text readability. We will adjust or replace the background to ensure the text is clearer and easier to read.
