### ISSUE TITLE
Peer Review by Team Insight Decoders

### ISSUE THREAD

**Issue by Hemanath17ua** [INFO-526-FA24/project-2-dream-jobs#11]
Hello Team Dream Jobs,

Strengths:
The poster and graphics are self-explanatory, effectively conveying the key information.
The design facilitates easy understanding without requiring extensive explanations.

Weaknesses:
Minor cosmetic adjustments could enhance the overall aesthetic appeal.
Text size inconsistencies need correction to improve readability and uniformity.

**Comment by SohanicX** [comment]
Hello,

Thank you for your valuable feedback and for highlighting the strengths of our poster! We're glad that the self-explanatory design and visuals effectively convey key information.

We appreciate your suggestions regarding cosmetic adjustments and text size inconsistencies. These have been noted, and we’ll ensure they are addressed to enhance the overall aesthetic and improve readability.
