### ISSUE TITLE
Peer Review by InfoCrew

### ISSUE THREAD

**Issue by tallapaneniv** [INFO-526-FA24/project-2-dream-jobs#12]
Strength - visualizations were easy to interpet, color for each plot worked well , data worked well with plots

Weakness - Background of poster

**Comment by SohanicX** [comment]
Thank you for your feedback! We're glad you found the visualizations easy to interpret and appreciated the color scheme and data alignment with the plots.

Regarding the background of the poster, we will revisit its design to ensure it complements the content better and enhances overall readability and aesthetics
