### ISSUE TITLE
peer_review by insight-decoders

### ISSUE THREAD

**Issue by Kaushik0802** [INFO-526-FA24/project-2-dream-jobs#2]
1. Full names and github names of reviewing team-
Rohith Singaravelu - @Rohith710
Kaushik Kumar - @Kaushik0802
Hemanath A - @Hemanath17ua
Hemant Kumar - @hemabk

2. Describe the goal of the project
The project’s goal is clearly defined and very practical. It aims to analyze the U.S. job market, focusing on trends, skills, and career pathways. This will offer recent graduates valuable insights into job demand, salary expectations, and industry-specific opportunities—essential information for making informed career choices.

3. Describe the data used or collected.
The dataset includes relevant variables such as job titles, required experience, qualifications, salary range, and job location. It seems well-suited to capture the nuances of different job roles across industries and locations, which should provide a solid foundation for uncovering meaningful trends.

4. Describe how the research question will be answered, e.g. what approaches / methods will be used.-
The team has outlined a strong approach. They plan to use descriptive statistics and visualizations to highlight demand trends across job roles and locations. Additionally, using text analysis on job descriptions to identify skill trends is a smart move, and trend analysis over time will help reveal shifts in demand, which will add an insightful layer to the findings.

5. Is there anything that is unclear from the proposal?
The proposal is mostly clear, but there are a couple of areas that could benefit from additional detail:
- Clarifying the strategy for handling inconsistent data, especially with text variables like job titles, would enhance transparency.
- If any predictive modeling is planned, specifying how it will be evaluated (e.g., accuracy metrics) would help clarify the analysis depth.

6. Suggestions for Improvements there anything that is unclear from the proposal?
- Model Evaluation: If any forecasting models are planned, it would help to outline how they’ll be evaluated.
- External Datasets: Consider supplementing the job market data with external sources (e.g., demographic or economic data) to provide additional context.
- Real-World Application: A discussion on how these insights could be used by career advisors or academic institutions would highlight the practical applications of this work.

7. What aspect of this project are you most interested in and would like to see highlighted in the presentation.-
The focus on skill trends is particularly compelling. This aspect will be valuable for students who want to align their skill development with in-demand roles, offering actionable insights for their career planning.

8. Provide constructive feedback on any issues with file and/or code organization.
For code organization, modular sections for data loading, cleaning, analysis, and visualization will be important. Including comments and annotations, especially for complex steps like text processing, would make the code easier to understand and follow.

Any Additional Feedback?
Overall, this is a thoughtfully designed project with clear relevance for students’ career goals. Adding a section on how the findings could inform career counseling or even curriculum adjustments would further boost its impact. Great job, DreamJobs team.

**Comment by Lucifer970901** [comment]
Thank you for the detailed feedback and thoughtful suggestions. 

While implementing predictive models is beyond the scope of this project, we aim to leverage insights from the collected data to provide a comprehensive overview of the current economy and job market. This will be achieved through visual storytelling, utilizing data visualizations to highlight trends, in-demand skills, salary expectations, and location-based job opportunities. 

Data will be extracted through web scraping from multiple job websites, such as LinkedIn, Glassdoor, and Indeed, ensuring a diverse and representative dataset. 

While career counseling and curriculum development are outside our scope, the actionable insights provided will empower students to make informed decisions about seeking career counseling and selecting curricula that align with their career aspirations and market demands.
