### ISSUE TITLE
Instructor Review 

### ISSUE THREAD

**Issue by annahoju** [INFO-526-FA24/project-2-dream-jobs#3]
Hello team Dream Jobs

Overall, your proposal indicates that you are set up for a success. The team has carefully considered the process of creating a data set (surveys and scraping) and exploring what jobs are wanted and available. 

Note that everyone should be active in GitHub and contributing to the project. I have discussed this with 2 team members that there is an issue with 1 team member.  All 4 should be contributing to the work. Therefore, the score below will be individual for teamwork based on what activity is recorded in GitHub. 

One area of consideration that I do not see is addressed int he proposal is the approach to the poster presentation. As a team, spend some time storyboarding the poster and consider how such an ambitious project will be translated into a poster.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |      3  |
| Proposal | 5         |    5    |
| Workflow | 1         |    1    |
| Teamwork | 1         |     1   |
| Total    | 10        |   9.75     |

**Comment by Ramtejavangari** [comment]
Thank you for your valuable feedback, Professor, and apologies for the delayed response. We ensured that everyone worked together to successfully complete this project, and we also addressed the concern regarding the poster presentation on the iShowcase day.

Regards,
Team Dream Jobs.
