### ISSUE TITLE
Team Pixels and Patterns

### ISSUE THREAD

**Issue by sindhugoshika** [INFO-526-FA24/project-2-dream-jobs#4]
Hello Team Dream Jobs,

I really liked your presentation and poster! It’s clear that your work will help people analyze job trends effectively. Your visualizations reflect how well you understand your data, questions, and outcomes.

I have a couple of suggestions:

For your second visualization, it would be great to highlight the job roles for mid-level experienced individuals (2–10 years), as many of our classmates fall into this category. This addition would be incredibly helpful.
In your first visualization, consider adding the number of years next to the title. This way, you won’t have to explain it repeatedly to everyone on iShowcase day.
Overall, fantastic job!

Team Pixels and Patterns

**Comment by SohanicX** [comment]
Thank you for the thoughtful suggestions and positive feedback! We've made the following updates based on your input:

For the second visualization, we've added a highlight for job roles targeting mid-level experienced individuals (2–10 years) to better cater to the interests of our classmates.
In the first visualization, we've included the number of years directly next to the title for improved clarity and to minimize the need for verbal explanations during iShowcase.
We appreciate your insights, and we’re glad you liked the overall work!
