### ISSUE TITLE
Peer Review of iShowcase Poster by Team DataWaves

### ISSUE THREAD

**Issue by iam-ajeetsingh** [INFO-526-FA24/project-2-dream-jobs#5]
**Hello Team 'DreamJobs',**

Your research topic is very relevant and interesting and the way of presenting the poster is impressive. 

I have following observations about the poster: 
**1. What is the good thing about the poster?**
You have made very Interesting observations and Inferences by using specific plots.  

**2. What can be improved?**
 Poster formatting and aesthetics have some scope of improvement and can be improved to make it look better.

**Overall Great Job , Team DreamJobs.**

**Comment by SohanicX** [comment]
Thank you for your feedback! We've made adjustments to the poster's formatting and aesthetics to enhance its overall appearance. These improvements include better alignment, consistent spacing, and a more visually appealing color scheme to ensure a polished and professional look.
