### ISSUE TITLE
Review from DataVizionaries

### ISSUE THREAD

**Issue by srikrish2812** [INFO-526-FA24/project-2-dream-jobs#6]
Topic: Analysis of Data related Jobs

Strength: The analysis of data and cloud related jobs in the US was done in a clear and detailed manner. The box plot and bar plot gives a good overview of the current US job market in the data related domains.

Weakness: The texts and the plots are not organized properly. It would make the poster more attractive if they were organized.

**Comment by SohanicX** [comment]
Thank you for your feedback! We've reorganized the texts and plots to improve the overall layout and visual appeal of the poster. The updated arrangement ensures better alignment and balance, making the poster more attractive and reader-friendly.
