### ISSUE TITLE
Review From Insight Spark

### ISSUE THREAD

**Issue by Sharanpazhanivel** [INFO-526-FA24/project-2-dream-jobs#7]
Strength:
The dataset is an excellent choice, capturing the interest of everyone in the class.

 Weakness:
Some plots, such as the density plot, could benefit from additional textual explanations to enhance interpretability.

**Comment by ronymacwan** [comment]
++ Adding below points as well.

Strength:
Job dataset chosen is excellent and highly engaging. It is relevant and interesting for everyone in the class.

Weakness:
The addition of more textual explanations would have been helpful, especially for certain plots (like the density plot), which may not be easily interpretable for everyone.

**Comment by SohanicX** [comment]
Thank you for the suggestion! We've added additional textual explanations to the plots, particularly the density plot, to enhance interpretability and ensure that the insights are clear to all viewers.
