### ISSUE TITLE
Review from team Data Nexus

### ISSUE THREAD

**Issue by SiddheshwarSinghNegi** [INFO-526-FA24/project-2-dream-jobs#9]
Strengths: The graphs are clear and self-explanatory, allowing the audience to quickly understand the data without requiring additional context. This demonstrates a thoughtful approach to visualization design, ensuring that the key insights are communicated effectively.

Weaknesses: The text elements within the project could benefit from resizing and rearrangement to improve readability and visual balance. In their current state, some text may appear either too small to read comfortably or too large, dominating the layout unnecessarily.

**Comment by SohanicX** [comment]
Thank you for your feedback! We've reviewed and addressed the concerns regarding text resizing and layout. The elements have been resized and rearranged to improve readability and ensure a visually balanced presentation.
